// MCL-DSP8x8 Firmware
// Author: Michael Larson
// Created: 3/20/2026
// Last modified: 3/21/2026
// Description: Firmware for ESP32-S3-WROOM-1U to control ADAU1452 and AK4619 chips for an 8 channel in, 8 channel out DSP device.
// Based on example Analog Devices code found here: https://wiki.analog.com/resources/tools-software/sigmastudio/tutorials/microcontroller

#include <Arduino.h>
#include "SigmaStudio\SigmaStudioFW.h"
#include "SigmaStudio\USER_SETTINGS.h"
#include <SPI.h>
#include "SigmaStudio\MCL-DSP8x8_IC_1.h"
#include "SigmaStudio\MCL-DSP8x8_IC_1_PARAM.h"

#define HEARTBEAT_PERIOD_MS 500
#define HEARTBEAT_LED 1

// Function prototypes
void DSP_HARD_RESET();
void initHeartbeat(); // Initialize heartbeat LED
void heartbeat(); // Toggle heartbeat LED state

bool heartbeatState = 1;
int heartbeatTime = 0;
int programTime = 0;

/**
 * This setup function is responsible for initializing hardware libraries.
 */
void setup() {
    initHeartbeat();
    delay(1000);              // 1 second startup delay
    Serial.begin(115200);    // Initialize the USB serial port for debug

    pinMode(18, INPUT);                // Set the I2C SDA pin high-impedance to avoid contention with SPI
    pinMode(19, INPUT);                // Set the I2C SCL pin high-impedance to avoid contention with SPI
    digitalWrite(DSP_SS_PIN, HIGH);    // Set SPI slave select line to initialize high
    pinMode(DSP_SS_PIN, OUTPUT);       // Enable SPI slave select pin
    SPI.begin();                       // Initialize the SPI library
}

void loop() {
    if (millis() > (heartbeatTime + HEARTBEAT_PERIOD_MS)) {
        heartbeatTime = millis();
        heartbeat();
    }

    if (millis() > (programTime + 10000)) {
        programTime = millis();
        // Drive Pin 6 of the USBi connector low to reset the DSP and SPI toggle if necessary.
        DSP_HARD_RESET();

        // default_download_IC_1, generated by SigmaStudio, will download the SigmaStudio program and start up the
        // DSP. It relies on a proper SPI or I2C implementation in SigmaStudioFW.h, which must be tailored to
        // the individual processor. and assigning pins correctly in USER_SETTINGS.h.
        default_download_IC_1();
    }
}

void DSP_HARD_RESET() {
    pinMode(DSP_RESET_PIN, OUTPUT);
    digitalWrite(DSP_RESET_PIN, LOW);
    delay(10);
    digitalWrite(DSP_RESET_PIN, HIGH);
    // This delay accounts for ADM811T reset generator hold time on ADAU1467 eval board, adjust
    // as needed
    delay(560);

    // Toggle the DSP into SPI mode by pulling the /SS pin low, then high, 3 times.
    for (uint8_t i = 0; i < 3; i++) {
        digitalWrite(DSP_SS_PIN, LOW);
        delayMicroseconds(10);
        digitalWrite(DSP_SS_PIN, HIGH);
        delayMicroseconds(10);
    }
}


// Initialize heartbeat LED
void initHeartbeat() {
  pinMode(HEARTBEAT_LED, OUTPUT);
  heartbeatTime = millis();
  return;
}

// Toggle heartbeat LED state
void heartbeat() {
  digitalWrite(HEARTBEAT_LED, heartbeatState);
  heartbeatState = !heartbeatState;
}